import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import SessionProviderServer from "../SessionProviderServer/SessionProviderServer";
import { SpeedInsights } from '@vercel/speed-insights/next';
import Navbar from "../component/pagesComponents/Navbar/Navbar";
import Footer from "../component/pagesComponents/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
  subsets: ["latin"],
  variable: "--font-exo",
});

export const metadata: Metadata = {
  title: "ECommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderServer>
            <Navbar />
            {children}
            <SpeedInsights />
            <Toaster position="bottom-right" duration={2000} richColors={true} />
            <Footer />
        </SessionProviderServer>
      </body>
    </html>
  );
}
